"""EDA page: dataset-wide exploratory analysis charts."""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src.config.settings import PATHS  # noqa: E402

from utils.data_loader import load_raw_train  # noqa: E402

st.set_page_config(page_title="EDA", page_icon="🔍", layout="wide")
st.title("🔍 Exploratory Data Analysis")

df = load_raw_train()

st.subheader("Summary Statistics")
col1, col2, col3 = st.columns(3)
col1.metric("Mean Daily Sales", f"{df['sales'].mean():.2f}")
col2.metric("Std Dev", f"{df['sales'].std():.2f}")
col3.metric("Max Daily Sales (single row)", int(df["sales"].max()))

st.divider()
st.subheader("Pre-computed Charts")
st.caption(
    "Generated by `src/visualization/eda.py` — run it again after updating the data to refresh these."
)

image_names = [
    ("eda_overall_trend.png", "Total daily sales across all stores/items"),
    ("eda_monthly_seasonality.png", "Sales distribution by month"),
    ("eda_dow_seasonality.png", "Mean sales by day of week"),
    ("eda_store_item_heatmap.png", "Mean sales heatmap (store x item)"),
    ("eda_top_bottom_items.png", "Best- vs worst-selling items"),
    ("stl_aggregate.png", "STL decomposition (aggregate)"),
    ("stl_example_series.png", "STL decomposition (example series)"),
]

for filename, caption in image_names:
    path = PATHS.images_dir / filename
    if path.exists():
        st.image(str(path), caption=caption, width="stretch")
    else:
        st.warning(
            f"{filename} not found — run `python -m src.visualization.eda` and "
            f"`python -m src.visualization.time_series_analysis` first."
        )
