"""SHAP Analysis page: global feature importance and per-feature impact."""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src.config.settings import PATHS  # noqa: E402
from src.utils.common import load_json  # noqa: E402

st.set_page_config(page_title="SHAP Analysis", page_icon="🧠", layout="wide")
st.title("🧠 SHAP Explainability")

st.caption(
    "Generated by `src/evaluation/shap_explainability.py`. Shows which features drive each "
    "model's predictions, computed via SHAP's TreeExplainer on a sample of validation rows."
)

available = sorted(p.stem.replace("shap_", "") for p in PATHS.reports_dir.glob("shap_*.json"))
if not available:
    st.warning(
        "No SHAP results found yet. Run `python -m src.evaluation.shap_explainability` "
        "(or see the docs for a one-liner) to generate them for a trained model first."
    )
    st.stop()

model_name = st.selectbox("Model", available)

summary_path = PATHS.reports_dir / f"shap_{model_name}.json"
summary = load_json(summary_path)

col1, col2 = st.columns(2)
summary_img = PATHS.images_dir / f"shap_summary_{model_name}.png"
bar_img = PATHS.images_dir / f"shap_importance_{model_name}.png"

if summary_img.exists():
    col1.image(str(summary_img), caption="SHAP Summary (beeswarm)", width="stretch")
if bar_img.exists():
    col2.image(str(bar_img), caption="Global Feature Importance", width="stretch")

st.subheader("Top Features by Mean |SHAP value|")
top_features = list(summary["mean_abs_shap"].items())[:15]
st.bar_chart({name: val for name, val in top_features})
