"""FastAPI service for the Retail Demand Forecasting system.

Run with:
    uvicorn api.app:app --reload

Endpoints:
    GET  /health       - liveness/readiness check
    POST /predict      - single (store, item, date) point prediction
    POST /forecast     - full 90-day horizon forecast for one (store, item)
    GET  /model-info   - metadata about the currently served model
    GET  /docs         - interactive OpenAPI docs (auto-generated by FastAPI)
"""

from __future__ import annotations

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from src.deployment.inference import _MODEL_PREFERENCE, get_inference_service
from src.utils.logging_utils import get_logger

from api.schemas import (
    ForecastPoint,
    ForecastRequest,
    ForecastResponse,
    HealthResponse,
    ModelInfoResponse,
    PredictRequest,
    PredictResponse,
)

logger = get_logger(__name__)

app = FastAPI(
    title="Retail Demand Forecasting API",
    description="Multi-series retail demand forecasting for inventory optimization (Store x Item, 90-day horizon).",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", response_model=HealthResponse, tags=["monitoring"])
def health() -> HealthResponse:
    """Report service health and whether a model is loaded and ready to serve."""
    try:
        service = get_inference_service()
        return HealthResponse(status="ok", model_loaded=True, model_name=service.model_name)
    except FileNotFoundError as exc:
        logger.warning("Health check found no trained model: %s", exc)
        return HealthResponse(status="degraded", model_loaded=False, model_name=None)


@app.post("/predict", response_model=PredictResponse, tags=["forecasting"])
def predict(request: PredictRequest) -> PredictResponse:
    """Predict sales for a single (store, item, date) combination."""
    try:
        service = get_inference_service()
        prediction = service.predict_single(request.store, request.item, request.date)
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    return PredictResponse(
        store=request.store,
        item=request.item,
        date=request.date,
        predicted_sales=round(prediction, 2),
        model_used=service.model_name,
    )


@app.post("/forecast", response_model=ForecastResponse, tags=["forecasting"])
def forecast(request: ForecastRequest) -> ForecastResponse:
    """Predict sales for the next ``horizon_days`` days for one (store, item) series."""
    try:
        service = get_inference_service()
        forecast_df = service.predict_horizon(request.store, request.item, request.horizon_days)
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    points = [
        ForecastPoint(
            date=row["date"].date(), predicted_sales=round(float(row["predicted_sales"]), 2)
        )
        for _, row in forecast_df.iterrows()
    ]
    return ForecastResponse(
        store=request.store, item=request.item, model_used=service.model_name, forecast=points
    )


@app.get("/model-info", response_model=ModelInfoResponse, tags=["monitoring"])
def model_info() -> ModelInfoResponse:
    """Return metadata about the currently served model, including its validation metrics."""
    try:
        service = get_inference_service()
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    return ModelInfoResponse(
        model_name=service.model_name,
        feature_count=len(service.feature_columns),
        validation_metrics=service.validation_metrics,
        available_models=_MODEL_PREFERENCE,
    )


@app.get("/", tags=["monitoring"])
def root() -> dict:
    """Redirect-style root endpoint pointing to the interactive docs."""
    return {"message": "Retail Demand Forecasting API. Visit /docs for interactive documentation."}
